### ISSUE TITLE
keycloak insists in serving cached gzipped theme content

### ISSUE THREAD

**Issue by ahristov314** [keycloak/keycloak-community#207]
For some reason keycloak insists in serving theme files cached in /tmp/kc-gzip-cache even though the original versions have been long updated or even deleted.  This only happens if the request accepts gzipped content.
(Full setup below)

I have a test keycloak 12.0.1 running in docker container under docker-compose as follows:
```
  #
  # KeyCloak SSO
  #
  keycloak:
    image: jboss/keycloak:12.0.1
    hostname: keycloak
    container_name: keycloak
    mem_limit: 2Gb
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
    environment:
      (omitted)
    volumes:
      - /system/public/keycloak/themes/agora:/opt/jboss/keycloak/themes/agora
      - /system/public/keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml

```
The standalone.xml is the one that comes with the base image, but with the caching disabled, specifically:
```
            <theme>
                <staticMaxAge>-1</staticMaxAge>
                <cacheThemes>false</cacheThemes>
                <cacheTemplates>false</cacheTemplates>

```

Now, I have a sample agora.css file in a custom theme folder (this is within the container):
```
[root@keycloak css]# pwd
/opt/jboss/keycloak/themes/agora/login/resources/css
[root@keycloak css]# ls -l
total 4
-rw-r--r-- 1 jboss root 67 Dec 29 16:16 agora.css

```

And this appears to be cached here:

```
[root@keycloak css]# pwd
/tmp/kc-gzip-cache/a03t4/login/agora/css
[root@keycloak css]# ls -l
total 8
-rw-r--r-- 1 jboss root  115 Dec 29 15:47 agora.css.gz
-rw-r--r-- 1 jboss root 3313 Dec 29 15:47 login.css.gz

```

Despite the fact that the css file is newer, keycloak insists in serving the cached one. That happens even if the original css file is deleted, or even if the container is shut down and restarted. This only happens, though, if the request is made with Accept-Encoding: gzip. If that is omitted, the fresh resource is served.

This serves the old stale resource:
curl --dump-header -H "Host: 192.168.81.129:8080"  -H "Accept-Encoding: gzip" -i  http://192.168.81.129:8080/auth/resources/a03t4/login/agora/css/agora.css 

This serves the new resource:
curl --dump-header -H "Host: 192.168.81.129:8080"  -H "Accept-Encoding: deflate" -i  http://192.168.81.129:8080/auth/resources/a03t4/login/agora/css/agora.css 

Deleting the whole cache folder does force the new content to be gzipped.

Am I doing anything wrong?
