### ISSUE TITLE
Keycloak.X 12.0.2 with Postgres

### ISSUE THREAD

**Issue by rgieseke** [keycloak/keycloak-community#229]
I was trying to use Postgres with the Keycloak.X Docker image provided at https://quay.io/repository/keycloak/keycloak-x?tag=latest&tab=tags

I'm getting the following error:
```
keycloak_1  | 2021-02-04 14:23:10,134 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://postgres:5432/keycloak
keycloak_1  | 2021-02-04 14:23:10,178 ERROR [org.key.cli.Picocli] (main) ERROR: Failed to start server using profile (none).
keycloak_1  | 2021-02-04 14:23:10,180 ERROR [org.key.cli.Picocli] (main) ERROR: Failed to obtain JDBC connection
keycloak_1  | 2021-02-04 14:23:10,180 ERROR [org.key.cli.Picocli] (main) ERROR: No suitable driver found for jdbc:postgresql://postgres:5432/keycloak
 ```
Are there any extra steps needed to enable Postgres?

When running with the default DB (without the two `KC_DB*` vars in the yaml config below) i get the following which includes `jdbc-postgres`:

```
keycloak_1  | 2021-02-04 14:25:42,771 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, jdbc-mariadb, jdbc-mysql, jdbc-postgresql, keycloak, mutiny, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-health, smallrye-metrics, vertx, vertx-web]
```

 My docker-compose.yaml is

```yaml
version: '3'

volumes:
  postgres_data:
    driver: local

services:

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    depends_on:
    - pgkeycloak
    image: quay.io/keycloak/keycloak-x:latest
    depends_on:
      - postgres
    environment:
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
    ports:
      - 8080:8080
```

**Comment by michael4screen** [comment]
I also discovered this. 
I could get around by building my own docker image on top and mounting a config file that contains the db vendor property.

keycloak_config.properties

```
db=postgres
metrics.enabled=true
proxy=edge
cluster=default
```

Dockerfile
```
FROM quay.io/keycloak/keycloak-x:12.0.2

WORKDIR /opt/jboss/keycloak

COPY config/keycloak_config.properties ./conf/keycloak_config.properties

RUN ./bin/kc.sh config --config-file ./conf/keycloak_config.properties
```

Then build the image an use it within your docker compose.

**Comment by rgieseke** [comment]
Many thanks for sharing, worked perfectly (just changed the Postgres port to 5432 for both)!

For testing i ended up with this

Dockerfile
```Dockerfile
FROM quay.io/keycloak/keycloak-x:12.0.2

WORKDIR /opt/jboss/keycloak

RUN ./bin/kc.sh config --db=postgres
```

docker-compose.yaml
```yaml
version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - 5432:5432

  keycloakx:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - 8080:8080
    depends_on:
      - postgres
```

Using with `docker-compose up --build`

This not yet merged PR (https://github.com/keycloak/keycloak-community/pull/173/files) might also be helpful to anyone reading along.
