### ISSUE TITLE
So many URLs are not well formed based on KEYCLOAK_FRONTEND_URL

### ISSUE THREAD

**Issue by Nefcanto** [keycloak/keycloak-community#294]
Hello

I just couldn't find a place where I can send this bug. Thus I'm reporting it here.

I ran an instance of Keycloak on docker, using MariaDB, and here's my `docker-compose.yml` file.

```
version: "3.9"
services: 
    accounts:
        image: jboss/keycloak:latest
        container_name: Accounts
        ports: 
            - 3131:8080
        environment: 
            - KEYCLOAK_FRONTEND_URL=https://accounts.zoodexchange.com/auth
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=some_password
            - DB_VENDOR=mariadb
            - DB_ADDR=database
            - DB_DATABASE=accounts
            - DB_USER=keycloak
            - DB_PASSWORD=some_password
        volumes:
            - /HolismHolding/Infra:/HolismHolding/Infra
            - /Temp/HolismHolding/Accounts:/Temp
    database:
        image: mariadb
        container_name: AccountsDatabase
        ports:
            - 3306:3306
        environment:
            - MARIADB_ROOT_PASSWORD=some_password
            - MYSQL_DATABASE=accounts
            - MYSQL_USER=keycloak
            - MYSQL_PASSWORD=some_password
        volumes:
            - /Temp/HolismHolding/Accounts/Database:/var/lib/mysql 
    pma:
        image: phpmyadmin:latest
        container_name: AccountsPma
        ports:
            - 3232:80
        environment: 
            - PMA_HOST=database

```

And I ran an instance of this configuration on my VPS. You can check it's protocol endpoints here:

https://accounts.zoodexchange.com/auth/realms/Development/.well-known/openid-configuration

The point is, a lot of the endpoint URLs are not respecting the `KEYCLOAK_FRONTEND_URL` environment variable. A lot of them simply point to `localhost:3131` which of course is not accessible on the internet. Because I expose all of my services via  NGINX and reverse proxy.

Just wanted to report this bug. Thank you.
