### ISSUE TITLE
Set custom issuer to generate jwt token in keycloak

### ISSUE THREAD

**Issue by aryanPatilhm2** [keycloak/keycloak-community#51]
Hi...I am trying using keycloak in my project with docker-compose and envoy as front proxy. While running locally, My proxy is running on https 443 port and keycloak is running on http 8080 port.
Whenever I use keycloak login for authentication from my angular application, It provide me the token as expected. But while validating this token with envoy authentication, as shown in below URL
https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto

It provide me 401 error.
```
Jwt issuer is not configured.
```

Below is my http filter for envoy
```
                http_filters:
                  - name: envoy.filters.http.jwt_authn
                    config:
                      providers:
                        jwtprovider:
                            issuer: http://localhost/auth/realms/example
                            remote_jwks:
                              http_uri:
                                # uri: http://localhost/auth/realms/example/.well-known/openid-configuration
                                uri: http://localhost/auth/realms/example/protocol/openid-connect/certs
                                cluster: keycloak-service
                            forward_payload_header: "example-token"
                      rules:
                      - match:  
                          prefix: "/backendapi/"
                        requires:
                          provider_and_audiences:
                            provider_name: jwtprovider
```

And cluster defined like below,
```
    - name: keycloak-service
      type: STRICT_DNS
      lb_policy: round_robin
      hosts:
        - socket_address:
            address: keycloak
            port_value: 8080
```
I read more regarding keycloak token generation. I found that keycloak use public URL as issuer while generating the token.
Is there any workaround to handle this issue? OR is it possible to set the custom issuer to generate jwt token in keycloak? While searching,  I have found following regarding this.
https://issues.redhat.com/browse/KEYCLOAK-6984
But I didn't get any workaround regarding docker from that.
Can you please help me?

Thanks in advance..
